# Generated by Django 4.2.6 on 2023-10-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_alter_code_createdat_alter_code_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='title',
            field=models.CharField(default='Código', max_length=100),
        ),
    ]
