# Generated by Django 4.2.6 on 2023-10-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_code_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='original',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
