# Generated by Django 4.2.6 on 2023-10-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_code_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(choices=[('c++', 'c++'), ('py', 'python'), ('c', 'c'), ('java', 'java'), ('c#', 'c#'), ('js', 'javascript')], default='c++', max_length=10),
        ),
    ]
