# Generated by Django 4.2.6 on 2023-10-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_code_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='human_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
