# Generated by Django 4.2.6 on 2023-10-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_alter_tag_human_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
