# Generated by Django 4.2.6 on 2023-11-14 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0011_alter_code_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
